server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.105:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 192.168.56.105:3306/guli_pms
    username: root
    password: Zkf520++
  redis:
    host: 192.168.56.105
